### ISSUE TITLE
AttributeError: 'ImportError' object has no attribute 'message'

### ISSUE THREAD

**Issue by The-Compiler** [marcus-oscarsson/pyqtconsole#1]
I just wanted to try `examples/inuithread.py` without `jedi` installed and got this:

```
Traceback (most recent call last):
  File "/home/florian/tmp/pyqtconsole/venv/lib/python3.4/site-packages/pyqtconsole/interpreter.py", line 6, in <module>
    import jedi
ImportError: No module named 'jedi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/inuithread.py", line 8, in <module>
    from pyqtconsole.console import PythonConsole
  File "/home/florian/tmp/pyqtconsole/venv/lib/python3.4/site-packages/pyqtconsole/console.py", line 8, in <module>
    from .interpreter import PythonConsoleProxy
  File "/home/florian/tmp/pyqtconsole/venv/lib/python3.4/site-packages/pyqtconsole/interpreter.py", line 8, in <module>
    print(ex.message)
AttributeError: 'ImportError' object has no attribute 'message'
```

I think this should be `print(str(ex))` instead.

**Comment by marcus-oscarsson** [comment]
Thanks @The-Compiler, I imagine that you are using Python 3 ?. I have not yet tested for python 3 so I'm happy to know how it works. I've fixed the attribute error, I have a bad habit of using .message. Ill do some testing for Python 3 within shortly.

**Comment by The-Compiler** [comment]
Oh, I didn't realize there's no official python3 support, sorry!

It seemed to work for me after that fix, but I only did a quick test - would be glad if it works!

**Comment by marcus-oscarsson** [comment]
Don't worry, I'm happy for the feedback. My intention is that it should work on Python 3 as well, but I'm developing on 2.7 just using -3 switch occasionally.
