### ISSUE TITLE
Crash for autocompletions

### ISSUE THREAD

**Issue by jacobwilliams** [marcus-oscarsson/pyqtconsole#25]
I get a crash when trying to use autocompletion for some modules. `sys` works, but `os` doesn't, for example.

So, type:

```python
IN [0]: import os
IN [1]: os.
```
then press tab, and I get:

```
Traceback (most recent call last):
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\jedi\cache.py", line 46, in wrapper
    return getattr(self, name)
AttributeError: 'MixedName' object has no attribute '_infer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\jedi\evaluate\compiled\access.py", line 120, in wrapper
    cache[key]
KeyError: 1414775657752

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\parso\cache.py", line 89, in load_module
    module_cache_item = parser_cache[hashed_grammar][path]
KeyError: '\\AppData\\Local\\Continuum\\anaconda3\\lib\\importlib\\_bootstrap_external.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\pyqtconsole\autocomplete.py", line 25, in eventFilter
    return bool(self.key_pressed_handler(event))
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\pyqtconsole\autocomplete.py", line 33, in key_pressed_handler
    intercepted = self.handle_tab_key(event)
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\pyqtconsole\autocomplete.py", line 52, in handle_tab_key
    self.trigger_complete()
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\pyqtconsole\autocomplete.py", line 87, in trigger_complete
    self.show_completion_suggestions(_buffer)
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\pyqtconsole\autocomplete.py", line 90, in show_completion_suggestions
    words = self.parent().get_completions(_buffer)
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\pyqtconsole\console.py", line 571, in get_completions
    return [comp.name for comp in script.completions()]
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\jedi\api\__init__.py", line 174, in completions
    completions = completion.completions()
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\jedi\api\completion.py", line 103, in completions
    return sorted(completions, key=lambda x: (x.name.startswith('__'),
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\jedi\api\completion.py", line 43, in filter_names
    k = (new.name, new.complete)  # key
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\jedi\api\classes.py", line 437, in complete
    return self._complete(True)
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\jedi\api\classes.py", line 406, in _complete
    if self._name.api_type == 'param' and self._stack is not None:
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\jedi\evaluate\compiled\mixed.py", line 90, in api_type
    return next(iter(self.infer())).api_type
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\jedi\cache.py", line 48, in wrapper
    result = func(self)
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\jedi\evaluate\compiled\mixed.py", line 85, in infer
    _create(self._evaluator, access_handle, parent_context=self.parent_context)
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\jedi\evaluate\compiled\access.py", line 125, in wrapper
    result = func(evaluator, obj, parent_context)
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\jedi\evaluate\compiled\mixed.py", line 204, in _create
    result = _find_syntax_node_name(evaluator, access_handle)
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\jedi\evaluate\compiled\mixed.py", line 150, in _find_syntax_node_name
    module_node = _load_module(evaluator, path)
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\jedi\evaluate\cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\jedi\evaluate\compiled\mixed.py", line 111, in _load_module
    cache_path=settings.cache_directory
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\parso\grammar.py", line 76, in parse
    return self._parse(code=code, **kwargs)
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\parso\grammar.py", line 97, in _parse
    module_node = load_module(self._hashed, path, cache_path=cache_path)
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\parso\cache.py", line 93, in load_module
    return _load_from_file_system(hashed_grammar, path, p_time, cache_path=cache_path)
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\parso\cache.py", line 113, in _load_from_file_system
    module_cache_item = pickle.load(f)
AttributeError: 'PythonErrorLeaf' object has no attribute 'original_type'
```

I'm using an Anaconda/Python 3 distribution on Windows.

**Comment by jacobwilliams** [comment]
Note: when I update to:
```
parso  0.5.1
jedi   0.15.1
```
It now works fine.

**Comment by coldfix** [comment]
I believe this should be closed too, since it appears to be a bug in an old version of jedi or parso.

**Comment by marcus-oscarsson** [comment]
Yes :)
