### ISSUE TITLE
pyside2 not supported

### ISSUE THREAD

**Issue by whattheserver** [marcus-oscarsson/pyqtconsole#51]
Is there a way to add Pyside2 support?

Error when trying to use this.
```
/home/someusername/PycharmProjects/SomeSecretProject/venv/bin/python /home/someusername/.PyCharm2019.3/config/scratches/scratch_31.py
Traceback (most recent call last):
  File "/home/someusername/PycharmProjects/SomeSecretProject/venv/lib/python3.6/site-packages/pyqtconsole/qt/__init__.py", line 107, in autodetect
    import PyQt5
ModuleNotFoundError: No module named 'PyQt5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/someusername/PycharmProjects/SomeSecretProject/venv/lib/python3.6/site-packages/pyqtconsole/qt/__init__.py", line 114, in autodetect
    import PyQt4
ModuleNotFoundError: No module named 'PyQt4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/someusername/PycharmProjects/SomeSecretProject/venv/lib/python3.6/site-packages/pyqtconsole/qt/__init__.py", line 120, in autodetect
    import PySide
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/someusername/.PyCharm2019.3/config/scratches/scratch_31.py", line 5, in <module>
    from pyqtconsole.console import PythonConsole
  File "/home/someusername/PycharmProjects/SomeSecretProject/venv/lib/python3.6/site-packages/pyqtconsole/console.py", line 6, in <module>
from .qt.QtCore import Qt, Signal, QThread, Slot, QEvent
from .qt.QtWidgets import QPlainTextEdit, QApplication, QHBoxLayout, QFrame
from .qt.QtGui import QFontMetrics, QTextCursor, QClipboard

  File "/home/someusername/PycharmProjects/SomeSecretProject/venv/lib/python3.6/site-packages/pyqtconsole/qt/__init__.py", line 154, in <module>
    autodetect()


def autodetect():
    """
    Auto-detects and use the first available QT_API by importing them in the
    following order:

    1) PyQt5
    2) PyQt4
    3) PySide
    """
    logging.getLogger(__name__).debug('auto-detecting QT_API')
    try:
        logging.getLogger(__name__).debug('trying PyQt5')
        import PyQt5
        os.environ[QT_API] = PYQT5_API[0]
        logging.getLogger(__name__).debug('imported PyQt5')
    except ImportError:
        try:
            logging.getLogger(__name__).debug('trying PyQt4')
            setup_apiv2()
            import PyQt4
            os.environ[QT_API] = PYQT4_API[0]
            logging.getLogger(__name__).debug('imported PyQt4')
        except ImportError:
            try:
                logging.getLogger(__name__).debug('trying PySide')
                import PySide
                os.environ[QT_API] = PYSIDE_API[0]
                logging.getLogger(__name__).debug('imported PySide')
            except ImportError:
                raise PythonQtError('No Qt bindings could be found')


if QT_API in os.environ:
    # check if the selected QT_API is available
    try:
        if os.environ[QT_API].lower() in PYQT5_API:
            logging.getLogger(__name__).debug('importing PyQt5')
            import PyQt5
            os.environ[QT_API] = PYQT5_API[0]
            logging.getLogger(__name__).debug('imported PyQt5')
        elif os.environ[QT_API].lower() in PYQT4_API:
            logging.getLogger(__name__).debug('importing PyQt4')
            setup_apiv2()
            import PyQt4
            os.environ[QT_API] = PYQT4_API[0]
            logging.getLogger(__name__).debug('imported PyQt4')
        elif os.environ[QT_API].lower() in PYSIDE_API:
            logging.getLogger(__name__).debug('importing PySide')
            import PySide
            os.environ[QT_API] = PYSIDE_API[0]
            logging.getLogger(__name__).debug('imported PySide')
    except ImportError:
        logging.getLogger(__name__).warning(
            'failed to import the selected QT_API: %s',
            os.environ[QT_API])
        # use the auto-detected API if possible
        autodetect()
else:
    # user did not select a qt api, let's perform auto-detection
    autodetect()


  File "/home/someusername/PycharmProjects/SomeSecretProject/venv/lib/python3.6/site-packages/pyqtconsole/qt/__init__.py", line 124, in autodetect
    raise PythonQtError('No Qt bindings could be found')
pyqtconsole.qt.PythonQtError: No Qt bindings could be found
```

Do not see this module on the github but it looks like this is referenced for the Pyside in the below places.

```
Variable
PYSIDE_API
Found usages
Usage in import statement
venv/lib/python3.6/site-packages/pyqtconsole/qt
QtCore.py
from . import PYSIDE_API
QtGui.py
from . import PYSIDE_API
QtNetwork.py
from . import PYSIDE_API
QtTest.py
from . import PYSIDE_API
QtWidgets.py
from . import PYSIDE_API
Value read
venv/lib/python3.6/site-packages/pyqtconsole/qt
__init__.py
autodetect
        elif os.environ[QT_API].lower() in PYSIDE_API:
            os.environ[QT_API] = PYSIDE_API[0]
QtCore.py
elif os.environ[QT_API] in PYSIDE_API:
QtGui.py
elif os.environ[QT_API] in PYSIDE_API:
QtNetwork.py
elif os.environ[QT_API] in PYSIDE_API:
QtTest.py
elif os.environ[QT_API] in PYSIDE_API:
QtWidgets.py
elif os.environ[QT_API] in PYSIDE_API:
Value write
venv/lib/python3.6/site-packages/pyqtconsole/qt
__init__.py
PYSIDE_API = ['pyside']
```

**Comment by whattheserver** [comment]
I updated the files for the qt converter and it looks to be working now for pysides2 when doing basic tests now. Will have to test more but i believe with the below version should work for all versions now universally

[qt.zip](https://github.com/marcus-oscarsson/pyqtconsole/files/4333761/qt.zip)

**Comment by coldfix** [comment]
pyside2 support was added recently, but has not been released as of yet. What version of pyqtconsole were you using (installed from PyPI or current master)?. A new version with this capabality will be released soon. If you continue to experience problems, please report back.

By the way, it is not very convenient to upload zip files, please paste code snippets inline if you can, or provide a pull-request directly.
