### ISSUE TITLE
Auto-complete crash with most recent jedi

### ISSUE THREAD

**Issue by lreiher** [marcus-oscarsson/pyqtconsole#59]
It looks like *pyqtconsole* is not compatible to the most recent *jedi* version 0.18.0.
Auto-completion on tab-key crashes with the following traceback.

```
Traceback (most recent call last):
  File "/home/rosuser/.local/lib/python3.8/site-packages/pyqtconsole/autocomplete.py", line 25, in eventFilter
    return bool(self.key_pressed_handler(event))
  File "/home/rosuser/.local/lib/python3.8/site-packages/pyqtconsole/autocomplete.py", line 33, in key_pressed_handler
    intercepted = self.handle_tab_key(event)
  File "/home/rosuser/.local/lib/python3.8/site-packages/pyqtconsole/autocomplete.py", line 52, in handle_tab_key
    self.trigger_complete()
  File "/home/rosuser/.local/lib/python3.8/site-packages/pyqtconsole/autocomplete.py", line 85, in trigger_complete
    self.show_completion_suggestions(_buffer)
  File "/home/rosuser/.local/lib/python3.8/site-packages/pyqtconsole/autocomplete.py", line 88, in show_completion_suggestions
    words = self.parent().get_completions(_buffer)
  File "/home/rosuser/.local/lib/python3.8/site-packages/pyqtconsole/console.py", line 603, in get_completions
    return [comp.name for comp in script.completions()]
AttributeError: 'Interpreter' object has no attribute 'completions'
```

According to [*jedi's* changelog](https://pypi.org/project/jedi/0.16.0/), the `completions` method of `jedi.Script` is deprecated since version 0.16.0.
It last appeared in version 0.17.2 ([see jedi/api/__init__.py#L285](https://github.com/davidhalter/jedi/blob/v0.17.2/jedi/api/__init__.py#L285)) and is missing in the current version 0.18.0.

**Comment by Norrica** [comment]
![image](https://user-images.githubusercontent.com/36772446/111610125-cfa2e680-87fc-11eb-90aa-0aa85b0493e9.png)

console.py, line 603.
```
        return [comp.name for comp in script.completions()]
```
changed to
```
        return [comp.name for comp in script.complete()]
```

seems to work for jedi 0.18.0

**Comment by RobertoRoos** [comment]
Created a pull request for this with your fix, sorry to take the credit @Norrica  :p
